# Generated by Django 5.2.7 on 2026-01-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('address', models.TextField()),
                ('created_date', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
